### ISSUE TITLE
Document how to contribute

### ISSUE THREAD

**Issue by kontrafiktion** [graalvm/graalpython#10]
Not really sure, whether you are ready to accept contributions.
If yes, please document

1) Basic setup
2) Limitations
3) How to handle CPython extensions using shared libraries

**Comment by timfel** [comment]
Thank you, and sorry for taking some time to get back to this. We've now added https://github.com/graalvm/graalpython/blob/master/CONTRIBUTING.md, I hope this clears up at least question 1. for you.

re 2. As for limitations, there are too many to list at this point, you'll find some when you try to run anything :)

re 3. I don't really understand the question, can you elaborate a bit what you mean by that? In particular, why would anything be required on our side of a CPython extension uses a system shared library.
