### ISSUE TITLE
Name scope of python script called from other language

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#105]
Is it possible to only call `data` in the following script, called from, say java?

```python
import polyglot
import datetime

@polyglot.export_value
def data(filename):
  print(datetime.datetime.now())
  print('I will open \"' + filename + '\"')

if __name__ == '__main__':
  data("crap.txt")
```

`Context.eval(Source source)` executes entire script including the `'__main__'`.

It'll be convenient if we can treat the existing python script as a module to be imported into
other languages.

**Comment by timfel** [comment]
There's not really a way to do this for us. I suggest you import this module from another.

**Comment by oroppas** [comment]
I thought it'd be brilliant if I can import my existing python module on my java application :(
Anyway, thank you for your help!
