### ISSUE TITLE
scipy requires venv

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#109]
Hi,

What makes `graalpython -m ginstall install scipy` mandate venv? Can't it be installed on user's local environment?

**Comment by timfel** [comment]
It is not possible to change the way SciPy chooses the Fortran compiler, other than changing the PATH. We need a custom wrapper around `gfortran` to compile SciPy to run on top of Sulong, and we need to put it somewhere. Installing in a venv is the best solution here.

In any case, you should always install everything inside a venv, anyway, never into the user's local environment. I won't list all the reasons here, but there's a good recent post here by a Python core dev here for some reasons :) https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by oroppas** [comment]
Thank you, @timfel

I was curious if I can bypass venv since #107.

**Comment by timfel** [comment]
#107 is fixed in master.

**Comment by oroppas** [comment]
Thanks!
