### ISSUE TITLE
Build error: DSL processor not run

### ISSUE THREAD

**Issue by wetneb** [graalvm/graalpython#115]
When building graalpython with `mx build`, the build fails because of missing classes not generated by the DSL processor:

```
Compiling com.oracle.graal.python with javac-daemon(JDK 11)... [dependency TRUFFLE_DSL_PROCESSOR updated]
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Compiling com.oracle.truffle.sl.test with javac-daemon(JDK 11)... [dependency TRUFFLE_DSL_PROCESSOR updated]
/home/user/graal/graalpython/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/common/HashingCollectionNodes.java:43: error: package com.oracle.graal.python.builtins.objects.common.HashingCollectionNodesFactory does not exist
import com.oracle.graal.python.builtins.objects.common.HashingCollectionNodesFactory.GetDictStorageNodeGen;
```
There are indeed no such generated classes in the `mxbuild` directory.
 
I am using OpenJDK 11 (set with `JAVA_HOME`) and OpenJDK 8 (set with `EXTRA_JAVA_HOMES`).

The full build logs are attached.
[log.txt](https://github.com/graalvm/graalpython/files/3965483/log.txt)

**Comment by timfel** [comment]
That's surprising, since we're testing this configuration in the CI. But clearly, the annotation processor doesn't run at all for you. We're not setting `EXTRA_JAVA_HOMES`, though, only JAVA_HOME to JDK11.

**Comment by wetneb** [comment]
I tried without any `EXTRA_JAVA_HOMES`, just with `JAVA_HOME` pointing to a fresh AdoptOpenJDK distribution of OpenJDK 11, and I get the same results.

**Comment by wetneb** [comment]
I tried again from scratch and I can't reproduce the issue - closing. Sorry for the noise!
