### ISSUE TITLE
[interop] invokeMember throws `PException` instead of `ArityException`

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#118]
`invokeMember` should throw an [`ArityException`](https://github.com/oracle/graal/blob/da471b0bb5616db29a99d64c94731d768bae14f3/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/ArityException.java#L51) in case the number of arguments is incorrect. At the moment, it throws a GraalPython-internal `PException` instead:

![image](https://user-images.githubusercontent.com/2368856/71381854-a84b7280-25d5-11ea-9898-c3a78c98a721.png)

Related issue: https://github.com/oracle/truffleruby/issues/1864

**Comment by timfel** [comment]
It's unlikely that we'll be able to fix this error - how would we distinguish it from any other type error, or an arity error of a method called inside that method?

**Comment by fniephaus** [comment]
I'm sure there are some edge cases in Python. But in common cases, it should be possible to check the [Signature](https://github.com/graalvm/graalpython/blob/8a48496de7ee2793f5babf485c1564e5da1bd08f/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/function/Signature.java) of a function/method before executing it in [`invokeMember`](https://github.com/graalvm/graalpython/blob/8a48496de7ee2793f5babf485c1564e5da1bd08f/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/PythonAbstractObject.java#L1205). Maybe [`GetSignatureNode`](https://github.com/graalvm/graalpython/blob/8a48496de7ee2793f5babf485c1564e5da1bd08f/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/nodes/builtins/FunctionNodes.java#L207) can be used for that?

Apart from that, I wonder if it would be possible to add something like `minimumNumberOfArgumentsOf(anInvocable/anExecutable)` to [`InteropLibrary`](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/interop/InteropLibrary.html)?
