### ISSUE TITLE
pytz.timezone doesn't work

### ISSUE THREAD

**Issue by zolstein** [graalvm/graalpython#119]
Running version 19.3.0 of both Graal and graalpython

After running `graalpython -m ginstall pytz`, I can import pytz but the method `pytz.timezone` for getting the tzinfo object associated with a timezone name doesn't work correctly. It raises an UnknownTimeZoneError for all timezones other than 'UTC'.
```
$ python3 -c "import pytz; print(pytz.timezone('US/Eastern'))"
US/Eastern
$ graalpython -c "import pytz; print(pytz.timezone('US/Eastern'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module '<string>'>
  File "/Users/zach/.local/lib/python3.7/site-packages/pytz/__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: US/Eastern
```
This seems to happen because the `all_timezones_set` doesn't have any entries.
```
$ python3 -c "import pytz; print(len(pytz.all_timezones), len(pytz.all_timezones_set))"
592 592
$ graalpython -c "import pytz; print(len(pytz.all_timezones), len(pytz.all_timezones_set))"
591 0
```
I haven't fully investigated, but I think this stems from `pytz`'s `LazySet` class which does some magic to... something something lazy loading. I don't totally understand it.

I can work around this issue by reassigning the `pytz.all_timezones_set` but then I see the following:
```python
>>> import pytz
>>> pytz.all_timezones_set = set(pytz.all_timezones)
>>> pytz.timezone('US/Eastern')
Traceback (most recent call last):
Unexpected values provided for FindNodeGen@38542168: [b'LMT\x00EDT\x00EST\x00EWT\x00EPT\x00', b'\x00', 0, NoValue], [PBytes,PBytes,Long,PNone]
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for FindNodeGen@38542168: [b'LMT\x00EDT\x00EST\x00EWT\x00EPT\x00', b'\x00', 0, NoValue], [PBytes,PBytes,Long,PNone]
```
This seems to stem from the following code snippet. Plausibly this could be expected to fail, depending on what unpack does, but if so it should have a patch and if not it may indicate a bug in the implementation.
```python
def build_tzinfo(zone, fp):
    head_fmt = '>4s c 15x 6l'
    head_size = calcsize(head_fmt)
    (magic, format, ttisgmtcnt, ttisstdcnt, leapcnt, timecnt,
        typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
```

**Comment by zolstein** [comment]
I dug a bit deeper. The issue stems from BytesBuiltins.FindNode. pytz winds up calling this with a Long value for the `start` argument but the specializations only expect `int`, so it fails to find a valid specialization and fails. I managed to fix this by adding specializations that accept either `long` or `Number`; after that, the REPL snippet works correctly. Haven't figured out the problem with LazySets yet.

**Comment by timfel** [comment]
Thank you for the report. If you feel like opening a PR with the fix, you're welcome to do so :) Otherwise we will apply the fix in the next days

**Comment by zolstein** [comment]
I've actually opened a PR at https://github.com/graalvm/graalpython/pull/121

**Comment by zolstein** [comment]
I've opened a second PR at https://github.com/graalvm/graalpython/pull/122 for the LazySet problem.

**Comment by msimacek** [comment]
Hi @zolstein, it seems your PR has fixed the problem so I believe this issue can be closed now. Feel free to comment or open a new issue if you still observe problems.
