### ISSUE TITLE
Lib random throws error

### ISSUE THREAD

**Issue by mathisloge** [graalvm/graalpython#12]
Hey there, 
i cant import the libary "random" inside of java.
```
import random
print(random.randint(0, 9))
```
these lines will throw an error. `org.graalvm.polyglot.PolyglotException: java.lang.ClassCastException: com.oracle.graal.python.builtins.objects.PNone cannot be cast to com.oracle.graal.python.builtins.objects.module.PythonModule`

if i run it with graalpyton testfile.py it runs without errors

**Comment by timfel** [comment]
When you run python inside of Java, you need to make sure to set `-Dpython.home` to point to the GraalVM directory `jre/languages/python`. We have to improve our error message here, but it's a symptom of not being able to find the standard library.

**Comment by timfel** [comment]
The error message has been improved and should be more indicative of what's wrong now. Closing
