### ISSUE TITLE
Make this available for installation using pyenv

### ISSUE THREAD

**Issue by thedrow** [graalvm/graalpython#125]
pyenv is the de-facto tool most developers use to install Python versions.
It would be much easier to try graalpython if it were installable using pyenv.

**Comment by timfel** [comment]
We'll look into it, we weren't sure if there's sufficient interest.

**Comment by timfel** [comment]
There's a PR open for pyenv: https://github.com/pyenv/pyenv/pull/1594

**Comment by timfel** [comment]
PR was merged
