### ISSUE TITLE
[interop] Iterables exposed as arrays, but not accessible

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#130]
The [`pycountry` package](https://pypi.org/project/pycountry/) exposes a list of all countries as an `pycountry.ExistingCountries` which implements [`__iter__` and `__len__`](https://github.com/flyingcircusio/pycountry/blob/master/src/pycountry/db.py#L95-L101). The following TruffleSqueak screenshot demonstrates that `pycountry.countries` appears correctly as an array-like object. However, it is not possible to access its values through the interop API. Either, iterables should not be exposed like this, or `InteropLibrary#readArrayElement` is not allowed to fail.

#### TruffleSqueak screenshot

![image](https://user-images.githubusercontent.com/2368856/81708137-55cdfe00-9471-11ea-8508-8f33d08f8941.png)

#### Python workspace
```python
import pycountry

pycountry.countries => ForeignObject[arraySize=249,memberSize=41]

str(type(pycountry.countries)) => '<class ''pycountry.ExistingCountries''>'

pycountry.countries[1] => `Error: TypeError: 'ExistingCountries' object is not subscriptable` (this is expected)

list(pycountry.countries)[1] => ForeignObject[memberSize=26]
```

#### Smalltalk workspace
```smalltalk
(Polyglot eval: 'python' string: 'pycountry.countries') => ForeignObject[arraySize=249,memberSize=41]
(Polyglot eval: 'python' string: 'pycountry.countries') at: 1
```

/cc @timfel

**Comment by timfel** [comment]
The issue is here: https://github.com/graalvm/graalpython/blob/master/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/PythonAbstractObject.java#L266

The `dataModelLibrary.isIterable(this)` check is incorrect here.

**Comment by fniephaus** [comment]
Thank you, @msimacek !
