### ISSUE TITLE
ProxyObject to dict conversions

### ISSUE THREAD

**Issue by tosha-220** [graalvm/graalpython#133]
Hi!
I try to pass ProxyObject converted from Map to python function.
This function has some type checks , like on list , dict and etc.
The problem is all proxy objects have 'foreign' type, so i can't check type properly.
Also i should use only python syntax without some interactions with java methods, so i cannot pass simple java map or using some java class checks.
This approach (using ProxyObject) working well with JS but in Python it doesn't work.
How can i use java map like dict in python scripts?

**Comment by timfel** [comment]
What you want is currently not possible in the interop protocol. It only works in JS because in JS a map and an object are the same thing, but in many other languages (including Python), the map namespace and the attribute namespace are different.

Can share a bit more detail about what you are trying to achieve? You probably shouldn't be using `isinstance` checks, but instead use polymorphism.

**Comment by tosha-220** [comment]
I need to make some transformations in json which i convert to Proxy objects and based on map value type make different transformations.
`Context context = Context.newBuilder().allowAllAccess(true).build();
String script = "def main(json):\n"
    + "    if isinstance(json, list):\n"
    + "        return 'list'\n"
    + "    elif isinstance(json, dict):\n"
    + "        return 'dict'\n"
    + "    else:\n"
    + "        return json.__class__.__name__ \n";
Source source = Source.newBuilder("python", script, "test.py").build();
context.eval(source);
Value mainFunction = context.getBindings("python").getMember("main");

mainFunction.execute(ProxyObject.fromMap(Map.of("field", "value")));
// value ='foreign'

mainFunction.execute(ProxyArray.fromList(List.of("field", "value")));
// value ='foreign'`
With isinstance or type() i can't archive that.
Scripts will be created by another team and if it is possible it will be better not to use not Python syntax in scripts. How can i use java map(or ProxyObject) in python scripts with values type check?

**Comment by timfel** [comment]
If you cannot change that code, you cannot. You could call `getClass().getSimpleName()` to get the Java class name.

**Comment by tosha-220** [comment]
I can change but i need to use python syntax only and work with map like with dict.
Thanks!

**Comment by tosha-220** [comment]
Sorry, one more question
Why when i call getBindings("js") it executes fast, less than second, but when i call getBindings("python") it can take up to 5 seconds?
