### ISSUE TITLE
str.format and f-strings ignore formatting options

### ISSUE THREAD

**Issue by zolstein** [graalvm/graalpython#136]
Using GraalVM and GraalPython 20.0.0.

The formatting options provided by str.format and f-strings broadly don't work. (E.g. padding, non-decimal number formatting.) The formatters can parse the options, but then fail to apply the defined format. By comparison, percent-formatting does seem to apply these options.

CPython:
```python
>>> '{:4}'.format('a')
'a   '
>>> '{:x}'.format(10)
'a'
>>> '{:03x}'.format(10)
'00a'
>>> f'{"a":4}'
'a   '
>>> f'{10:x}'
'a'
>>> f'{10:03x}'
'00a'
```

GraalPython:
```python
>>> '{:4}'.format('a')
'a'
>>> '{:x}'.format(10)
'10'
>>> '{:03x}'.format(10)
'10'
>>> f'{"a":4}'
'a'
>>> f'{10:x}'
'10'
>>> f'{10:03x}'
'10'
```

**Comment by timfel** [comment]
Thank for the report. As it happens, we just scheduled working on this last week, and we should have this fixed for the next release.

**Comment by zolstein** [comment]
Fantastic. Any chance you can update this ticket when the fix comes into master?

**Comment by steve-s** [comment]
The examples mentioned in the report are now working correctly on GraalPython master.

**Comment by msimacek** [comment]
Closing as per previous comment.
