### ISSUE TITLE
[interop] "TypeError: object of type 'TextIOWrapper' has no len()"

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#141]
### Repro

```
$ polyglot --jvm --shell
GraalVM MultiLanguage Shell 20.1.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  JavaScript version 20.1.0
  Python version 3.8.2
js> Polyglot.eval("python", "import sys; sys")
TypeError: object of type 'TextIOWrapper' has no len()
```

*Tested with GraalVM CE 20.1.0 on macOS Catalina.*

**Comment by msimacek** [comment]
The exception is not from the `eval`, but from the printer that tries to display the returned value. The underlying problem is the same as you already reported in #130 - we shouldn't report iterables as arrays.
