### ISSUE TITLE
Python -> Java Method

### ISSUE THREAD

**Issue by lvca** [graalvm/graalpython#145]
Hi guys,

I can't figure out how to make this work. I've got a simple Java method in the class "Intraday".

```
public float gapPerc() {
   ...
}
```

The from this Python script the IF doesn't work:
```
import polyglot

Intraday = polyglot.import_value('Intraday')

def beginTrading():
  if ( Intraday.gapPerc() >= 0.1 ): 
    return "{ 'invest': true, 'reason': 'Gapper Found' }"
```

No errors, just the method return is not evaluated. I set a breakpoint and I've checked that the Java `gapPerc()` method is called (and returns > 0.1).

Any idea?

**Comment by lvca** [comment]
Sorry, I found the error and it was that the polyglot settings were off.

**Comment by timfel** [comment]
Glad you found the problem :)
