### ISSUE TITLE
Inconsistent component name for macOS

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#147]
Other languages and GraalVM itself use `darwin` while GraalPython uses `macos` for macOS component names:

![image](https://user-images.githubusercontent.com/2368856/88286019-63fd8d80-ccf0-11ea-815b-6658a880dd32.png)

**Comment by timfel** [comment]
This is consistent with the TruffleRuby standalone:
![Screenshot from 2020-07-23 14-32-22](https://user-images.githubusercontent.com/46235/88286635-58f72d00-ccf1-11ea-8b43-c80e7b544edc.png)

**Comment by timfel** [comment]
Note the difference between "installable" as in something to plug into a GraalVM and the standalone version. Is it a problem for you in some automation or other?

**Comment by fniephaus** [comment]
Oh right, didn't know there was a GraalPython standalone, makes sense. Not a big problem on my side, but still it's inconsistent to the installables.
