### ISSUE TITLE
Some documents seem outdated

### ISSUE THREAD

**Issue by Glavo** [graalvm/graalpython#158]
In [Jython.md](https://github.com/graalvm/graalpython/blob/master/docs/user/Jython.md):

> 
> Instead, you will have to import one of the classes you are interested in directly:
> ```
> import javax.swing.Window as Window
> ```

This doesn't seem to work:
```
>>> import javax.swing.Window as Window
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
ModuleNotFoundError: No module named 'javax'
>>> java.io.ByteArrayInputStream(b"foobar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'java' is not defined
```

> The Python-style iteration of Java `java.util.Enumerable`,
> `java.util.Iterator`, or `java.lang.Iterable`  is not supported. For these, you will have to use a
> `while` loop and use the `hasNext()` and `next()` (or equivalent) methods.

It seems that this feature is now supported: 
```
>>> from java.util import List
>>> for str in List.of("A", "B", "C"):
...   print(str)
...
A
B
C
>>>
```

**Comment by timfel** [comment]
> import javax.swing.Window as Window

You have to have those classes on the classpath, of course.

> java.io.ByteArrayInputStream(b"foobar")

This example is assumed to be run in conjunction with the prior examples, so you need to do `import java` first.

> It seems that this feature is now supported:

Indeed it now works by coincidence for some Java types, but only those that allow indexed access.

**Comment by Glavo** [comment]
> > import javax.swing.Window as Window
> 
> You have to have those classes on the classpath, of course.

Sorry, I was misled by the documentation, the actual `javax.swing.Window` class does not exist (I think this is also a problem with the documentation). However, for existing classes, this problem still exists:

```
>>> import javax.swing.JWindow as JWindow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
ModuleNotFoundError: No module named 'javax'
>>> JWindow = java.type("javax.swing.JWindow")
>>> win = JWindow()
```

> > java.io.ByteArrayInputStream(b"foobar")
> 
> This example is assumed to be run in conjunction with the prior examples, so you need to do `import java` first.

In fact, import java does not solve the problem:

```
>>> import java
>>> java.io.ByteArrayInputStream(b"foobar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'java' has no attribute 'io'
>>>
>>> import java.io.ByteArrayInputStream
>>> java.io.ByteArrayInputStream(b"foobar")
<foreign object at 0x10b3ea72>
```

**Comment by Glavo** [comment]
After my attempts, directly importing classes that are not in the `java` package requires the option `--python.EmulateJython` to be turned on. I think this should also be noted in the document

```
$ $GRAALVM_HOME/bin/graalpython --jvm --experimental-options --python.EmulateJython
Python 3.8.2 (Sun Aug 23 15:26:19 CST 2020)
[Graal, GraalVM CE, Java 11.0.8] on linux
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> import javax.swing.JWindow as JWindow
>>> JWindow()
```

**Comment by timfel** [comment]
Ah, I assumed you were already running with the emulate Jython flag, it is noted in that document that you have to use that in the first paragraph. But thanks for the `Window` -> `JWindow` typo notice, we will fix that

**Comment by Glavo** [comment]
> Ah, I assumed you were already running with the emulate Jython flag, it is noted in that document that you have to use that in the first paragraph. But thanks for the `Window` -> `JWindow` typo notice, we will fix that

This is what the documentation says:
> Some features of Jython are more expensive at runtime, and thus are hidden behind a command line flag on Graal: `--python.EmulateJython`.

Some examples below do not need this flag to run, and the section [Exceptions from Java](https://github.com/graalvm/graalpython/blob/master/docs/user/Jython.md#exceptions-from-java) declares:

> Catching all kinds of Java exceptions comes with a performance penalty and is only enabled with the --python.EmulateJython flag.

so I thought all functions that require this flag will be specifically noted in the document. Sorry for misunderstanding the meaning of the document.

**Comment by Glavo** [comment]
I noticed some more documentation issues:

* The link to  reference in [README](https://github.com/graalvm/graalpython#trying-it) is broken:

> ### Trying it
> 
> To try it, you can use the bundled releases from
> [www.graalvm.org](https://www.graalvm.org/downloads/). For more information and
> some examples of what you can do with it, check out the
> [reference](https://www.graalvm.org/docs/reference-manual/languages/python/). <<[HERE]

* In [Interoperability.md](https://github.com/graalvm/graalpython/blob/master/docs/user/Interoperability.md#java-interoperability), wrong way to construct BigInteger: 

> Finally, to interoperate with Java (only when running on the JVM), you can use
> the `java` module:
> ```python
> import java
> BigInteger = java.type("java.math.BigInteger")
> myBigInt = BigInteger(42)
> myBigInt.shiftLeft(128)            # public Java methods can just be called
> myBigInt["not"]()                  # Java method names that are keywords in
>                                    # Python can be accessed using "[]"
> byteArray = myBigInt.toByteArray()
> print(list(byteArray))             # Java arrays can act like Python lists
> ```

In fact, `BigInteger` does not have a constructor that accepts a single integer, it should be constructed using the `valueOf`:

```
>>> BigInteger = java.type("java.math.BigInteger")
>>> myBigInt = BigInteger(42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid instantiation of foreign object
>>> myBigInt = BigInteger.valueOf(42)
>>> print(myBigInt.toString())
42
```

**Comment by timfel** [comment]
Good catches thank you!

**Comment by pekkaklarck** [comment]
Link to Jython info from the main README is broken as well. It points to

https://github.com/graalvm/graalpython/blob/master/docs/user/JYTHON.md

but the correct one seems to be

https://github.com/graalvm/graalpython/blob/master/docs/user/Jython.md
