### ISSUE TITLE
rc6 won't execute script if it's given as `/dev/stdin` (and won't report error either)

### ISSUE THREAD

**Issue by findepi** [graalvm/graalpython#17]
### rc5
```
$ bash -c "graalpython /dev/stdin <<<'print(2**42)'"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
4398046511104

$ echo 'print(2**42)' | graalpython /dev/stdin
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
4398046511104
```

### rc6
```
$ bash -c "graalpython /dev/stdin <<<'print(2**42)'"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
4398046511104

$ echo 'print(2**42)' | graalpython /dev/stdin
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
```

i.e. the second call didn't print anything

### Repro env
For reproducing, I use isolated docker environment.
```Dockerfile
FROM debian:stable

ARG GRAAL_VERSION=1.0.0-rc6

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && rm -r "/var/lib/apt/lists"/*

RUN curl -fsSL https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-${GRAAL_VERSION}-linux-amd64.tar.gz -o graalvm.tar.gz
RUN tar xf graalvm.tar.gz
ENV PATH=/graalvm-ce-${GRAAL_VERSION}/bin:/bin:/usr/bin
RUN gu install -c org.graalvm.python
```

**Comment by findepi** [comment]
Note: `program <<< "text"` and `echo text | program` are _not_ equivalent, at least on my machine.
In the former case, the program can open `/dev/stdin/`, read it, seek(0), read it again.
In the latter case, seek would fail.

My _guess_ would be that graalpython does something like that: reads the input once, seeks back/rewinds (here some error is swallowed), reads again (nothing is read, since we didn't seek). Thus, script to be executed is considered empty.

**Comment by findepi** [comment]
Also, if you happen to be testing this with docker... 
`docker run image program <<< "text"` doesn't behave like `program <<< "text"`.
In the former case, the input is read by `docker` client program and _probably_ actively forwarded to the `program`, so it behaves like `echo "text" | program`. The latter case's behavior is different, as shown above.

**Comment by timfel** [comment]
Thanks for the report, nothing comes to mind immediately that would've caused this, we're looking into it.

**Comment by timfel** [comment]
This will (finally) be fixed with the upcoming rc9

**Comment by findepi** [comment]
Thanks for fixing this.
