### ISSUE TITLE
gu install python -> Unknown component: python

### ISSUE THREAD

**Issue by AdamMcM** [graalvm/graalpython#173]
I have seen others with the error, but I have not found a solution yet.  I am on windows using the jdk 8 version of graalvm (openjdk version "1.8.0_262")

```
gu install python
Downloading: Component catalog from www.graalvm.org
Error: Unknown component: python
```

**Comment by tmillich** [comment]
Currently im suffering under the same problem.

**Comment by msimacek** [comment]
Unfortunately, graalpython is not yet available on Windows, so gu doesn't have anything to download there. Windows support is tracked in #156, so if you don't mind I'll close this issue as a duplicate. If you'd like to get the error message improved, please open an issue for gu in [graal repository](https://github.com/oracle/graal)

**Comment by aaa1999** [comment]
> Unfortunately, graalpython is not yet available on Windows, so gu doesn't have anything to download there. Windows support is tracked in #156, so if you don't mind I'll close this issue as a duplicate. If you'd like to get the error message improved, please open an issue for gu in [graal repository](https://github.com/oracle/graal)

Today I ran a comman as "gu install python" on ubuntu. The same error happend again. What's wrong?

**Comment by msimacek** [comment]
@aaa1999 please open an issue in [graal repository](https://github.com/oracle/graal)

**Comment by thorlaksson** [comment]
@liudonghua123 I have exactly same problem Error: Component "python" is not available in catalog.  ;(

**Comment by msimacek** [comment]
@thorlaksson There's no Windows support in the current release. See https://github.com/oracle/graalpython/issues/156 for tracking windows support
