### ISSUE TITLE
Binary build?

### ISSUE THREAD

**Issue by lambdaq** [graalvm/graalpython#18]
Hi, is it possible to provide `release` binaries for Oracle/CentOS/Debian using native image so we don't have to install JVM?

**Comment by ansalond** [comment]
Hello, thanks for your interest in our implementation of Python.

Would you like to have a standalone Graal.Python CE release with just the native launcher and the support files, like we do for TruffleRuby?
https://github.com/oracle/truffleruby/releases
https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc6/truffleruby-1.0.0-rc6-linux-amd64.tar.gz

**Comment by lambdaq** [comment]
@ansalond  Yes that's exactly what I want. 

A native launcher would be insanely useful for ppl like me.

**Comment by ansalond** [comment]
Thanks for the feedback. I plan to provide a standalone release of Python, but we first need to fix the integration with Sulong (LLVM). Without this, such standalone release would be able to run only trivial examples. I will keep you updated, but unfortunately I don't have an ETA yet.

**Comment by msimacek** [comment]
I belive the standalone releases are being provided already as requested and thus this issue can be closed. Please comment if you disagree
