### ISSUE TITLE
Build and Usage Instructions

### ISSUE THREAD

**Issue by kjeet** [graalvm/graalpython#2]
I was experimenting with the graalpython following the directions from https://www.graalvm.org/docs/reference-manual/graal-updater/

I noticed that none of the installed jars seemed to contain SignalModuleBuiltins, so I figured I'd try to build this project myself but I can't seem to find build instructions.

Thanks!

**Comment by fniephaus** [comment]
I agree that additional instructions would be useful. But since GraalPython uses [mx](https://github.com/graalvm/mx), you should be able to build it with `mx build`.

**Comment by kjeet** [comment]
I don't know if this is correct but I was able to build it by first locally building:
graal with the directions here: https://github.com/oracle/graal/blob/master/tools/README.md
then checkout out sulong and built that with mx build and then could even start building graalpython.

I had to comment out the block of code from graalpython:
mx.graalpython/mx_graalpython.py:532: mx_sdk.register_graalvm_component...
but that allowed the jars to complete building!

I can run a "Hello Python!" with the following (the CoreHome and StdLibHome set in java):
CP=:.:../JARS/graal-sdk.jar:../JARS/truffle-api.jar:../JARS/graalpython.jar
jdk10/bin/java -cp $CP HelloPolyglot

but if I run context.eval("python", "import platform") I get:
Exception in thread "main" ImportError: cannot import name 'monotonic'
	at <python> <module '../JARS/pyl/lib-python/3/subprocess.py'>(../JARS/pyl/lib-python/3/subprocess.py:54-56:1620-1696)

And it's true I'd expect "from time import monotonic as _time" from subprocess.py to fail. TimeModuleBuiltins.java declares @CoreFunctions(defineModule = "time") but has no mention of 'monotonic'.

(I just saw you response as I was typing this up)

**Comment by timfel** [comment]
@kjeet As you noticed, `import platform` is one of the many modules that doesn't work right now. The reason why you had to comment that block of code in `mx_graalpython` is that the build process is subject to change, but that is still an ongoing process. We'll have build instructions once the dust has settled a little bit :)

**Comment by kjeet** [comment]
Awesome.
Anything I can do to help speed that along? or is this not a good stage to try to onboard as a contributor?
I'm a huge fan of jython and I'd love to see this get to the same level.

**Comment by timfel** [comment]
Thanks for the offer - at this point contributions will be difficult to integrate due to many moving parts. In a few weeks and after a couple of more RCs the situation should improve and then contributions would be easier.

**Comment by kjeet** [comment]
Interesting. So did that platform.py code never work? or was it relying on functionality the got removed some how?

Is the python code forked from somewhere?
