### ISSUE TITLE
`graalpython --polyglot` fails with "Could not find launcher"

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#25]
**Steps to reproduce:**
1. Download GraalVM 1.0.0 RC8 EE for macOS
2. Install Python via `gu`
3. Launch `../graalvm-ee-1.0.0-rc8/Contents/Home/bin/graalpython --polyglot`

**Result:**
```bash
$ ../graalvm-ee-1.0.0-rc8/Contents/Home/bin/graalpython --polyglot
ERROR: Could not find launcher 'com.oracle.graal.python.shell.GraalPythonMain'
[1]    45618 exit 1     ../bin/graalvm-ee-1.0.0-rc8/Contents/Home/bin/graalpython --polyglot
```

**Expected result:**
Interactive Python shell "with all other guest languages accessible" as suggested by `--help` option.

**Comment by timfel** [comment]
Indeed, you have to rebuild the image (`bin/gu rebuild-images polyglot`), otherwise the native polyglot image won't be available. Alternatively, you can use `bin/graalpython --jvm --polyglot`.

@ansalond Do you think we could somehow get a better error message in this case?

**Comment by ansalond** [comment]
Done: https://github.com/oracle/graal/commit/1e537b0d4b22eb13361c17099be24aeaadb96850

**Comment by fniephaus** [comment]
Thanks!
