### ISSUE TITLE
Graalpython stucked after help()

### ISSUE THREAD

**Issue by THDevelop** [graalvm/graalpython#26]
To the procedure:
after which graalpython is started and help() is entered hangs GraalVM.

What did you want to do?.:
in help() you can query modules that can be used in Python,
since graalpython modules are unknown to me I wanted to find out about them.

**Comment by timfel** [comment]
Is this on the latest rc?

**Comment by timfel** [comment]
Note that help(modulename) will work for modules you have already imported. The help feature that lists all available modules won't work. It's not a priority, but I expect it will just start working as we continue to support more of the base language, but I cannot give you an estimate of when that'll be.

**Comment by timfel** [comment]
This is fixed in rc10.
