### ISSUE TITLE
[Interop] UnsupportedSpecializationException when calling polyglot.export_value with wrong parameters

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#30]
Repro via polyglot shell:
```bash
GraalVM MultiLanguage Shell 1.0.0-rc10
Copyright (c) 2013-2018, Oracle and/or its affiliates
  JavaScript version 1.0
  Python version 3.7.0
  R version 3.4.0
  Ruby version 2.4.4
Usage:
  Use Ctrl+L to switch language and Ctrl+D to exit.
  Enter -usage to get a list of available commands.
python> import polyglot
python> polyglot.export_value('o', object())
Internal error occured: org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for ExportSymbolNodeGen@29bcf51d: [o, <object object at 0x1e54a6b1>], [String,PythonObject]
Run with --verbose to see the full stack trace.
```

Expected result: value is correctly exported.

**Comment by fniephaus** [comment]
Just looked at the impl of [ExportSymbolNode](https://github.com/graalvm/graalpython/blob/7e15bd15868deb8fdee828e7cd64254830bd4ac1/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/modules/InteropModuleBuiltins.java#L229) only to realize I'm using `export_value` wrong. `polyglot.export_value(object(), 'o')` works as intended. However, I don't think `UnsupportedSpecializationException`s should leak, for example, into the shell.

**Comment by ppisl** [comment]
I think we can close this issue. It works for me in the recent builds.
