### ISSUE TITLE
NumPy float32 error

### ISSUE THREAD

**Issue by qunaibit** [graalvm/graalpython#32]
Hi,

Thank you for supporting NumPy and all the hard work.

I tried to create a `float32` array but I got an error.

```py
np.array([1,2,3,4], dtype=np.float32)
```
error:
```java
java.lang.IllegalStateException: Missing LLVM builtin: @llvm.x86.sse.cmp.ss
```
`float64` is fine though.

Is there a prerequisite that I missed?

**Comment by timfel** [comment]
No, you're not missing anything, that's an actual missing builtin in Sulong. We'll take a look, thanks for trying it out :)

**Comment by oroppas** [comment]
This bug seems to be already fixed, at least in master?

**Comment by timfel** [comment]
Yes, it's fixed, I forgot to close the issue.
