### ISSUE TITLE
[Interop] Foreign objects do not understand __getattribute__/__str__/__repr__/...

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#36]
Example:
```
GraalVM MultiLanguage Shell 1.0.0-rc10
Copyright (c) 2013-2018, Oracle and/or its affiliates
  JavaScript version 1.0
  Python version 3.7.0
js> Polyglot.eval('python', 'lambda x: x.__repr__()')(Object.create(null))
NameError: Unknown identifier: __repr__
        at <python> anonymous(<eval>:1:10-21)
        at <js> :program(<shell>:1:49-69)
```

It looks like [`TruffleObjectBuiltins`](https://github.com/graalvm/graalpython/blob/c31bc609cc7c730e30bf23473a7477abc5f58d58/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/foreign/TruffleObjectBuiltins.java) is missing an implementation for [`__GETATTRIBUTE__`](https://github.com/graalvm/graalpython/blob/c31bc609cc7c730e30bf23473a7477abc5f58d58/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/nodes/SpecialMethodNames.java#L64).

Related: https://github.com/graalvm/graaljs/issues/101

**Comment by timfel** [comment]
the fix is included in rc12
