### ISSUE TITLE
Module object (`itertools`) has no attribute `cycle`

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#39]

**Comment by timfel** [comment]
Thank you for this issue. Our itertools are currently implemented in pure Python under lib-graalpython/itertools.py, and they are not complete since we are implementing them as we need them. I've put this on my list :)

**Comment by KOLANICH** [comment]
```python
def cycle(it):
	while(True):
		for el in iter(it):
			yield el
```

**Comment by KOLANICH** [comment]
PyPy contains some code in docstrings claimed to be equivalent to their impls.
 
https://github.com/mozillazg/pypy/blob/master/pypy/module/itertools/interp_itertools.py#L772

**Comment by timfel** [comment]
Yes, unfortunately we found that oftentimes some piece of code will assume more than mere functional equivalence and will want to, for example, subclass the `cycle` type, so we'll actually provide a class.

**Comment by timfel** [comment]
The `cycle` class is included in rc12

**Comment by KOLANICH** [comment]
Works. Thank you.
