### ISSUE TITLE
__class__ is not available

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#40]
```python
class A:
   def b(self):
      return __class__()
```

**Comment by timfel** [comment]
Interesting, I'd never see that pattern. `self.__class__()` works, obviously, but we don't set the `__class__` cell correctly, it appears.

**Comment by KOLANICH** [comment]
`self.__class__` is the actual class
`__class__` is the class in which member the stuff is defined

```python
class A:
    def a(self):
        print(__class__, self.__class__)
class B(A):
   def b(self):
        print(__class__, self.__class__) #B, B
        self.a() # A, B
B().b()
```

**Comment by timfel** [comment]
Yes, indeed :-)
As I said, the issue is that we don't set the `__class__` cell in the class definition function scope

**Comment by cosminbasca** [comment]
Issue has been resolved, `__class__` cell var is set correctly in the function definition scope

**Comment by timfel** [comment]
This fix is included in rc12

**Comment by KOLANICH** [comment]
Works. Thank you.
