### ISSUE TITLE
Importing classes from jar is unobvious

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#43]
Here is how to import classes from a jar:

```python
from os import pathsep as PATH_sep
import java
ClassLoader = java.type("java.lang.ClassLoader")
scl = ClassLoader.getSystemClassLoader()
sys = java.type("java.lang.System")

origClassPath = sys.getProperty("sys.class.path")

dedupClassPath=OrderedDict()
for el in origClassPath.split(PATH_sep):
	dedupClassPath[el]=True

for f in libDir.glob("*.jar"):
	el=str(f.absolute())
	dedupClassPath[el]=True

classPathz=PATH_sep.join(dedupClassPath.keys())

sys.setProperty("sys.class.path", classPathz)
Main=scl.loadClass("a.package.in.a.jar.Main")
```

There are lot of issues here.

1. `java.type` returns only types built into Java
2. classpath cannot be set up right using `java` object
3. python `import` statement is not used (it is possible to write a loader using the stuff  above).
4. This way of loading java classes is not documented in GraalPython docs. I had to spend some time googling Java classes to do that.
5. Only java classes are clearly loaded this way, not `scala` ones (I can still use them as Java classes and it works fine, but it requires some perversions and type info like default arguments is missing and is not populated into `__annotations__`).

Probably it should look like
```python
from java.classes.a.package.in.a.jar import Main
```
This can even be implemented purely in python via a custom module loader wrapping the above code.

Some keywords to make this issue more searcheable:
`How to import a class from a jar into graalvm graalpython python.`

**Comment by timfel** [comment]
As of RC15, at least the import part works for classes that are already on the classpath.

For classes in the `java` package, it works directly:
`from java.util import ArrayList`
For others, the `java` prefix is required, e.g.:
`from java.com.oracle.graal.python import PythonLanguage`

We still need to add a convenient API to add things to the classpath dynamically.

**Comment by timfel** [comment]
We have APIs to do add to the classpath now (`java.add_to_classpath`). Also, we now support the commandline option `--python.EmulateJython`, which allows you to import any Java class using `import` statements.
