### ISSUE TITLE
Bytecode caching

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#44]
GraalPython starts up very slowly. It may make sense to cache preprocessed bytecode.

**Comment by timfel** [comment]
We don't use bytecode, so this won't be an option. We are working on startup performance, but for fast startup we're focused on the SVM build

**Comment by timfel** [comment]
SVM startup from a preinitialized context is faster than CPython now on my machine. The Java startup time will likely not get orders of magnitude better anymore, given how much code has to run during startup, but with Context sharing, it can at least warm up and goes to under 100ms after a while.

**Comment by KOLANICH** [comment]
Thanks for the hint. Gonna try that.
