### ISSUE TITLE
NameError: name 'PyCF_ONLY_AST' is not defined

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#53]
```
>>> import ast
>>> line = '__version__ = \"0.0.1\"'
>>> ast.literal_eval(line.split('=', 1)[1].strip())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
NameError: name 'PyCF_ONLY_AST' is not defined
```

**Comment by fangerer** [comment]
Hi Ryuta,
thanks for reporting. The underlying problem is that we did not fully implement the `ast` module yet (to be more precise, the `_ast` module). And the reason for this is that our internal AST representation is completely different from CPython's representation.
Could you please provide your use case of the `ast` module?

**Comment by oroppas** [comment]
Hi Florian,

I was trying to build pyfilesystem (https://github.com/PyFilesystem/pyfilesystem2) which requires appdirs (https://github.com/ActiveState/appdirs) which happens to use the `ast` module. So, the priority is not as high as other modules like `pandas`.

**Comment by oroppas** [comment]
The same error happens in atomicwrites (https://github.com/untitaker/python-atomicwrites)
which is required to run test in pytest (https://github.com/pytest-dev/pytest).

**Comment by timfel** [comment]
@oroppas just an update, we can install and run pytest now, provided you disable assertion rewriting:
```
graalpython -m pytest \
            --assert=plain \
            --tb=no \
            --continue-on-collection-errors
```

**Comment by oroppas** [comment]
@timfel,

Thanks for the update!

**Comment by oroppas** [comment]
Closing since `import ast` does not emit `NameError: name 'PyCF_ONLY_AST'` anymore.
