### ISSUE TITLE
pandas.read_csv throws error

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#54]
I tried to read `data.csv`

```
"a" "b" "c"
1 2 3
4 5 6
7 8 9
```

but

```
>>> import pandas as pd
>>> pd.read_csv('data.csv', sep=' ')
java.lang.ClassCastException: com.oracle.graal.python.builtins.objects.cext.PythonNativeObject cannot be cast to java.lang.Boolean
```

**Comment by fangerer** [comment]
Hi Ryuta,
we are already aware of this problem and supporting `pandas` is on our list. Chances are good that we support `read_csv` soon.

**Comment by oroppas** [comment]
Hi Florain,

I can the issue is fixed in the master branch. Thanks!
