### ISSUE TITLE
gu install python not working. 

### ISSUE THREAD

**Issue by bogorman** [graalvm/graalpython#6]
I am on OSX. Not sure if that is the problem. Should this be pre installed?

$ /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/lib/installer/bin/gu install -cv org.graalvm.python
Downloading: Component catalog
Receiving 4 kB: Done.
Processing component archive: Component org.graalvm.python
Preparing to install Component org.graalvm.python, contains org.graalvm.python, version 1.0.0-rc1 (org.graalvm.python)
Checking requirements of component Graal.python (org.graalvm.python), version 1.0.0-rc1
	Requires Graal Version = 1.0.0-rc1, GraalVM provides: 1.0.0-rc1
	Requires Architecture = amd64, GraalVM provides: amd64
	Requires Operating System = darwin, GraalVM provides: darwin
Downloading: Component org.graalvm.python
Receiving 0 kB: Error: Package for component org.graalvm.python is not accessible at https://github.com/graalvm/graalpython/releases/download/vm-1.0.0-rc1/python-installable-macos-amd64.jar

There are no releases available in the releases directory. Both R and ruby installed fine. Should I use another link for the install?

**Comment by lukasstadler** [comment]
The release tag went missing due to a problem on our side - should be working again now.
Sorry for the inconvenience!

**Comment by bogorman** [comment]
great. works now.
