### ISSUE TITLE
`__class_getitem__` is not supported

### ISSUE THREAD

**Issue by timfel** [graalvm/graalpython#66]
I was mistaken - `import typing` is indeed broken since our update to 3.7 stdlib (we were on 3.6.5 before). This is because it now uses `__class_getitem__` which we don't support, yet.

_Originally posted by @oroppas in https://github.com/graalvm/graalpython/issues/47#issuecomment-478415735_

**Comment by oroppas** [comment]
@timfel, I confirm the fix.

**Comment by timfel** [comment]
The fix was released with rc15
