### ISSUE TITLE
native launcher peformance

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#69]
What would be the expected performance, especially startup time for native launcher of graalpython? I'm curious if mine is in reasonable range for the current graalpython implementation.

```
$ time graalpython -c "print('hello world')"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
hello world

real	0m2.315s
user	0m1.871s
sys	0m0.591s
```

CPython on my system as reference:
```
$ time python -c "print('hello world')"
hello world

real	0m0.090s
user	0m0.044s
sys	0m0.009s
```

Here's how I build `graalpython`. In `graal/vm`, 

```
$ mx --dynamicimports /substratevm,/tools,sulong,/graalpython build
```

Thanks in advance.

**Comment by timfel** [comment]
This is expected at the moment, especially when you have some local packages installed. Most of the time is spent parsing the `site`.
```
~ > time ./graalpython-native -S -c "print('Hello world')"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Hello world

real    0m0.408s
user    0m0.337s
sys     0m0.072s
```
vs
```
~ > time ./graalpython-native -c "print('Hello world')"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Hello world

real    0m2.495s
user    0m1.972s
sys     0m0.656s
```

**Comment by timfel** [comment]
The other big chunk is spent in some patching that we do on startup by loading `pyio` from the standard library. If we disable that:
```
~ > time ./graalpython-native -S -c "print('Hello world')"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Hello world

real    0m0.027s
user    0m0.009s
sys     0m0.019s
```

**Comment by oroppas** [comment]
Hi @timfel,

Disabling import of `site` and `pyio` look identical. They both can be disabled by `-S`?

**Comment by timfel** [comment]
No, disabling the `pyio` import is not possible without modifying Python code in `lib-graalpython/__builtins_patches__.py`. And they're not identical, without `pyio` is 10x faster real than just without site

**Comment by timfel** [comment]
It's not something I would recommend, many things will break in other code paths, because the built-in `io` module is just good enough to get started, we use `pyio` as a Python-level implementation of the full `io` module

**Comment by timfel** [comment]
Pre-loading of the `_pyio` module is now done for the native image on master, so with the next release, using `-S` is enough to get the `~0.03s` real time startup. We are still working on improving the performance of running the `site` module so full startup is as fast as possible

**Comment by timfel** [comment]
Native launcher has good performance and even parsing additional files is faster now that we replaced with a completely new parser.
