### ISSUE TITLE
unknown encoding ascii

### ISSUE THREAD

**Issue by jmikedupont2** [graalvm/graalpython#77]
Test case
=======
https://github.com/jmikedupont2/graal-python-tests/blob/master/build/test_email.py

Test Output
=========
https://github.com/jmikedupont2/graal-python-tests/blob/master/build/test_email.txt

This found this issue while trying to import pip

**Comment by oroppas** [comment]
I don't see this issue in master branch.

**Comment by jmikedupont2** [comment]
ok, any build instructions for building master? n00b here.

**Comment by timfel** [comment]
It's an issue only with the native installable in rc16 only. We're on it and it'll be fixed soon.

**Comment by jmikedupont2** [comment]
vielen herzlichen Dank! :)

**Comment by jmikedupont2** [comment]
I am still looking for a way to build this graalpython from scratch, do you have any instructions?

**Comment by timfel** [comment]
This hopefully helps to get you started: https://github.com/graalvm/graalpython/blob/master/doc/CONTRIBUTING.md

**Comment by oroppas** [comment]
This is how I build graalpython on vm suite on Arch Linux:

```
git clone https://github.com/oracle/graal.git
git clone https://github.com/graalvm/graalpython.git
git clone https://github.com/graalvm/mx.git

cd graal/vm

JAVA_HOME=$HOME/packages/graal/graal-jvmci-8/openjdk1.8.0_212/linux-amd64/product \
PATH=$PATH:$HOME/packages/graal/mx \
mx --max-cpus 1 --dynamicimports /substratevm,/tools,sulong,/graalpython build
```

The binaries will be in `graal/vm/latest_graalvm_home/bin`

To build graal-jvmci-8:

```
git clone https://github.com/graalvm/graal-jvmci-8.git

cd graal-jvmci-8

JAVA_HOME=/usr/lib/jvm/java-8-openjdk \
PATH=$PATH:$HOME/packages/graal/mx \
DISABLE_HOTSPOT_OS_VERSION_CHECK=ok \
mx build
```
