### ISSUE TITLE
backtrace missing path

### ISSUE THREAD

**Issue by jmikedupont2** [graalvm/graalpython#78]
Traceback does not contain the fully qualified path.

example:
https://github.com/jmikedupont2/graal-python-tests/blob/master/build/test_email.txt

**Comment by fangerer** [comment]
Hi jmikedupont2, sorry haven't commented on your issue for such a long time and thanks for reporting this problem. I'm happy to announce that we have implemented a fix.

- Florian

**Comment by jmikedupont2** [comment]
thanks I am going to take another shot at graal
