### ISSUE TITLE
[Interop] Simple polyglot example is throwing an error 

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalpython#80]
Running the below command gives an error:

```
graalpython  example-python-js-interop.py
```

```
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "example-python-js-interop.py", line 1, in <module 'example-python-js-interop.py'>
  File "_bootstrap.py", line 1066, in __import__
  File "_bootstrap.py", line 985, in _gcd_import
  File "_bootstrap.py", line 968, in _find_and_load
  File "_bootstrap.py", line 955, in _find_and_load_unlocked
ModuleNotFoundError: ModuleNotFound: 'polyglot'. No module named 'polyglot'
```
` example-python-js-interop.py` contains the code in https://www.graalvm.org/docs/reference-manual/languages/python/#interoperability.

Is this using the python package `polyglot`, see https://pypi.org/project/polyglot/

**Comment by timfel** [comment]
You have to pass `--jvm --polyglot` (it says a few lines above the code in that documentation)

**Comment by timfel** [comment]
Ah, I only now noticed your last line... The polyglot package from PyPI has nothing to do with the example, `polyglot` is a built-in module in Graal Python

**Comment by neomatrix369** [comment]
Starting rc19 or (19.0.0) we will also need to do the below:

```
$GRAALCE_HOME/bin/gu update graalpython
```

followed by

```
$GRAALCE_HOME/bin/gu rebuild-images python
```

**Comment by neomatrix369** [comment]
> You have to pass `--jvm --polyglot` (it says a few lines above the code in that documentation)

Not sure how I missed this, silly of me.

**Comment by timfel** [comment]
> ```
> $GRAALCE_HOME/bin/gu update python
> ```

No, on a fresh install, `gu install python` is still enough.

> ```
> $GRAALCE_HOME/bin/gu rebuild-images python
> ```

No, this is not needed if you pass `--jvm`

**Comment by neomatrix369** [comment]
All of this is good info and I have been learning about them in the last week or so. I'll be happy to amend the docs or suggest someone from your team does it. It will help with smooth execution of the examples and zero issues raised.

**Comment by msimacek** [comment]
I'm afraid the repo is not public, at least I don't see it mirrored anywhere publicly. The generated HTML is published to https://github.com/oracle/graal/tree/gh-pages, so maybe you could try to outline the changes in the HTML version, make a PR against `gh-pages` and have somebody from the team make the corresponding changes to the internal source. Or just suggest the edit in some other way.

**Comment by msimacek** [comment]
We have changed how the webpage is built since I commented. Now you can contribute to the Python part of documentation by changing the files in `docs/user` and they will be propagated to graalvm.org by a bot.

**Comment by neomatrix369** [comment]
> We have changed how the webpage is built since I commented. Now you can contribute to the Python part of documentation by changing the files in `docs/user` and they will be propagated to graalvm.org by a bot.

I will give it a whirl!

**Comment by msimacek** [comment]
I believe there is no work remaining on our side for this, so I'd prefer to close this issue
