### ISSUE TITLE
Unexpected `UnsupportedMessageException` when called from Ruby

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#84]
## Repro
```java
polyglot --jvm --shell
GraalVM MultiLanguage Shell 19.0.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  Python version 3.7.0
  Ruby version 2.6.2
js> python>
python> from collections import deque
python> d = deque(maxlen=42)
python> import polyglot
python> polyglot.export_value(d, 'd')
deque([], maxlen=42)
python> js>
js> Polyglot.import('d').maxlen
42
js> ruby>
ruby> Polyglot.import('d')
<foreign>
ruby> Polyglot.import('d').maxlen
Internal error occured: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.RaiseException: Message not supported. (UnsupportedMessageException)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.create(UnsupportedMessageException.java:118)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObject$PExecuteNode.doExecute(PythonAbstractObject.java:783)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObjectFactory$PExecuteNodeGen.executeAndSpecialize(PythonAbstractObjectFactory.java:549)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObjectFactory$PExecuteNodeGen.execute(PythonAbstractObjectFactory.java:531)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObject.invokeMember(PythonAbstractObject.java:427)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(PythonAbstractObjectGen.java:833)
	from com.oracle.graal.python.builtins.objects.PythonAbstractObjectGen$InteropLibraryExports$Cached.invokeMember(PythonAbstractObjectGen.java:816)
	from com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:3104)
	from com.oracle.truffle.api.interop.LegacyToLibraryNode.sendInvoke(LegacyToLibraryNode.java:272)
	from com.oracle.truffle.api.interop.ForeignAccess.sendInvoke(ForeignAccess.java:395)
Translated to internal error (RuntimeError)
Run with --verbose to see the full stack trace.
ruby>
```

I'm guessing there's a bug in TruffleRuby (or they need to upgrade to interop 2.0, see https://github.com/oracle/truffleruby/issues/1690). Nonetheless, maybe better to double check if an exception should be thrown in this GraalPython node:

https://github.com/graalvm/graalpython/blob/87542731652fe88cfdc6fcb471fd1f40b590bac9/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/PythonAbstractObject.java#L771-L796

**Comment by fangerer** [comment]
AFAICS from the stack trace and the Ruby issue, we are doing everything right.
According to the Truffle documentation of `invokeMember`, we should raise `UnsupportedMessageException` if the member is not invocable. And it clearly isn't. Before a member is invoked, the _other side_ should use `isMemberInvocable` to test if that is possible.
I guess the problem is that Ruby tests if the member exists (and it exists) and then just invokes without further checks.
The question is, even if we avoid raising the exception, what should we actually do? The only thing is to silently swallow the error and that sounds incorrect to me.

**Comment by timfel** [comment]
This clearly looks like a Ruby bug.

**Comment by fniephaus** [comment]
Confirmed by @chumer (https://github.com/oracle/truffleruby/issues/1690#issuecomment-493005173) and it looks like @eregon is going to fix this in TruffleRuby.
