### ISSUE TITLE
Literal String Interpolation (PEP 498) not supported

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#85]
### Describe the Bug

Since python 3.6, Literal String Interpolation ([PEP 498](https://www.python.org/dev/peps/pep-0498/)) is supported. The following should produce the same result:

```
name = "max"
"This is my name {}".format(name)
f"This is my name {name}"
```

### Steps to Reproduce

Open graalpython shell from GraalVM CE 19.0.0:
```
$ graalpython
Python 3.7.0 (Thu Apr 04 12:16:00 PDT 2019)
[GraalVM CE, Java 1.8.0_202] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> a = 32
>>> f"{a}"
```
### Expected Behavior

```
>>> f"{a}"
'32'
```

### Actual Behavior

```
>>> f"{a}"
'{a}'
```

/cc @janehmueller

**Comment by timfel** [comment]
Yes, this is a known bug which we're also tracking internally. It will take a while to get this fixed, we are working on a new parser which will make this easier.

**Comment by ppisl** [comment]
I think we can close this issue. I have implemented the basic support of the literal string interpolation.
