### ISSUE TITLE
Incorrect argument handling in polyglot shell

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#86]
## test.py
```python
import sys
print(sys.argv)
```

## Expected behavior
```
$ graalpython test.py --foo
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
['test.py', '--foo']
```

## Misbehavior in polyglot shell
```
$ polyglot --jvm test.py --foo
['--foo']
```

Tested in GraalVM CE 19.0.0 on macOS.

/cc @janehmueller

**Comment by timfel** [comment]
We cannot fix this. Running this in the polyglot shell is akin to doing an "eval" of the contents of test.py, not like running the script.
