### ISSUE TITLE
The `resource` module is not implemented yet

### ISSUE THREAD

**Issue by zhangkaizhao** [graalvm/graalpython#9]
Hello. Seems some specific modules are not implemented yet.
For example, the `resource` module, which should locate on path like
`/usr/lib/python3.6/lib-dynload/resource.cpython-36m-x86_64-linux-gnu.so`
(using Python 3.6 as example).
The official documentation for the `resource` module is here: https://docs.python.org/3.7/library/resource.html .

Here is my test on Arch Linux using the AUR package https://aur.archlinux.org/packages/graalpython-bin

```
[kaizhao@zbox ~]$ uname -a
Linux zbox 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux
[kaizhao@zbox ~]$ graalpython --version
Graal Python 3.7.0 (GraalVM CE Native 1.0.0-rc3)
[kaizhao@zbox ~]$ graalpython -c "import resource"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "_bootstrap.py", line 1066, in __import__
  File "_bootstrap.py", line 985, in _gcd_import
  File "_bootstrap.py", line 968, in _find_and_load
  File "_bootstrap.py", line 955, in _find_and_load_unlocked
ModuleNotFoundError: ModuleNotFound: 'resource'. No module named 'resource'
```

Although this is a specific module just for Unix like systems, some third packages/tools may depend on it. For example:
https://github.com/ipython/ipython/blob/master/IPython/utils/timing.py
https://github.com/saltstack/salt/blob/develop/salt/utils/verify.py
https://github.com/saltstack/salt/blob/develop/salt/utils/vt.py
https://github.com/lilydjwg/swapview/blob/master/bench.py
etc.
I have read the "Python Compatibility" on https://www.graalvm.org/docs/reference-manual/languages/python/#python-compatibility .
And is there any plan for such issues?
Thanks!

**Comment by timfel** [comment]
Hi,

currently, we are focusing on a very narrow path to get some scientific computing packages working. Any modules on that path will be prioritized. Although we eventually plan to support all of Python, we cannot promise anything about when a particular module will be supported.

I'll close this issue for now, it'll be some time before we get to this.

**Comment by zhangkaizhao** [comment]
Got it. Thank you!

**Comment by harshkhanna** [comment]
In v21 of graalvm, if we exec a Python script via the Java context... 
In the above scenario the py script does a require requests etc... and it still throws - Exception in thread "main" ModuleNotFoundError: No module named 'requests'

But then if you call graalpython then the script runs fine... any clues please

**Comment by msimacek** [comment]
@harshkhanna When embedded in Java, you need to evaluate `import site` first to make installed packages available.

**Comment by harshkhanna** [comment]
Hi Michael

I did that :)

[image: image.png]

ModuleNotFoundError: No module named 'requests'
        at
org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:347)
        at ExecPolyglot$1.run(ExecPolyglot.java:28)
        at java.base/java.lang.Thread.run(Thread.java:834)

Thanx! Harsh

**Comment by msimacek** [comment]
@harshkhanna I don't see the image. Can you please post the code you're using?

**Comment by harshkhanna** [comment]
Yep absolutely!

*<ping.py>*
import site
import polyglot
import requests
response = reqs.get('http://www.google.com', timeout=0.50)
print(response.status_code)     # To print http response code
print(response.text)            # To print formatted JSON response
print('Testing 123')


*<Getting Invoked from Graal Java>*
File file = new File("/home/harsh/polyglot-test", "ping.py");
assert file.getName().endsWith(".py") : "Imagine proper file";

try {
  String language = Source.findLanguage(file);
  Source source = Source.newBuilder(language, file).build();

  try (Context context =
Context.newBuilder("python").allowNativeAccess(true).allowIO(true).allowPolyglotAccess(PolyglotAccess.ALL).build())
{
       context.eval(source);
  }
} catch (Throwable e) {
  e.printStackTrace();
 }

**Comment by msimacek** [comment]
Thank you. I tried you example and I needed to add two things:
- Since you're using virtualenv (I'm assuming), you need to tell it where it is. This can be done by passing the path to the `python` executable in the virtualenv as `python.Executable` context option.
- For some reason, it also needs host access. I'll need to investigate why.

So you can change you context creation to:
```
Context.newBuilder("python")
  .allowNativeAccess(true)
  .allowIO(true)
  .allowPolyglotAccess(PolyglotAccess.ALL)
  .allowHostAccess(HostAccess.ALL)
  .option("python.Executable", "path-to-your-virtualenv/bin/python")
  .build()
```
Or if you don't care about the access, you can allow everything using `.allowAllAccess(true)`.

**Comment by harshkhanna** [comment]
Hi Michael

Thanx a lot for helping here... I made the changes but the same error
persists.

BTW, I am not using a virtualenv - is that mandatory to setup?

                    try (Context context = Context.newBuilder("python")
                                                  .allowNativeAccess(true)
                                                  .allowIO(true)
*                                                  .allowAllAccess(true)*

.allowPolyglotAccess(PolyglotAccess.ALL)
*
.option("python.Executable", "/usr/bin/python3")*
                                                  .build())
                    {
                        context.eval(source);
                    }

Error -
ModuleNotFoundError: No module named 'requests'
        at
org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:347)

Harsh

**Comment by msimacek** [comment]
Yes, we currently don't support installing packages outside of virtualenv. We will in the future, but not in the current release. You can make the virtualenv and install `requests` into it using:
```
graalpython -m venv my-virtualenv
my-virtualenv/bin/python -m ginstall install requests
```
Then you use `my-virtualenv/bin/python` as the executable in the code I posted.

**Comment by harshkhanna** [comment]
Thank you sir. It worked!

One more question for you - I was trying to wrap the Context/Source in a
Java Runnable/Thread - idea being to fork off multiple python scripts
simultaneously from Graal. But it was hitting some exceptions deep in Graal
stack

Can you comment if a concurrent execution via Context would be supported
and how best can that be achieved?

Regards, Harsh

**Comment by msimacek** [comment]
Yes, it is supported with one context per thread - you create a new separate context for each thread and run your script there. If you did it this way and hit an exception it could be a bug. If that's the case, could you please open a new issue?

**Comment by harshkhanna** [comment]
Thanx Michael... much appreciated.

I retried it and it worked by creating a new context per thread.. must be
an operator error in the code. Let me come back if I find something.

Thanx again!
Harsh
