### ISSUE TITLE
[Question / Discussion] GraalVM suite build fails building graalpython with out-of-memory error

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalpython#92]
Error logs:
```
[snipped]
OpenJDK 64-Bit GraalVM 19.2.0-dev warning: INFO: os::commit_memory(0x0000000638500000, 2553282560, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2553282560 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/circleci/project/graal/vm/hs_err_pid28105.log
Error: Image build request failed with exit status 1

Building graalpython.image failed
1 build tasks failed
Exited with code 1
```

Detailed logs: https://circleci.com/gh/neomatrix369/awesome-graal/624

**THIS MIGHT NOT BE AN ISSUE OF THE BUILD PROCESS, BUT A GOOD EARLY TOPIC OF DISCUSSION**

**Comment by timfel** [comment]
If fails generating the native-image. Maybe @gilles-duboscq knows who could answer why. Maybe it's just honestly out of memory. How much ram do those circleci machines have?

**Comment by neomatrix369** [comment]
> It fails generating the native-image. Maybe @gilles-duboscq knows who could answer why. Maybe it's just honestly out of memory. How much ram do those circleci machines have?

8 GB, and you are right it is probably out of memory when building reach that stage. Although I was thinking is there any work being done to be able to overcome these issues. 
The whole build project and building process are only going to grow with the project - maybe building in small chunks and putting them together is an option?

I haven't started to look closely into how the build processes work but it's something I have on mind since long.

Building smaller chunks means many benefits. And fails faster in case we want to be able to detect regressions.

**Comment by timfel** [comment]
Well, you can always tell it not build the native images all the time, or selectively not build some native images. I forget what they are, but there's some environment variables defined in the vm build python files to do that

**Comment by neomatrix369** [comment]
> Well, you can always tell it not build the native images all the time, or selectively not build some native images. I forget what they are, but there's some environment variables defined in the vm build python files to do that

Thanks for the insight.

What's the benefit of building them and can they be built later on? And if native images are not built does it mean we get less performant artifacts?

**Comment by gilles-duboscq** [comment]
8GB is too tight to build non-trivial native images at the moment

If you don't build a native-image of graalpython, it will have slower start-up.

* In the `vm` directory, running `mx graalvm-show` should give you an overview of what is being built and in particular, you will see the various native-images (native launchers & libraries).
* `--force-bash-launchers=true` will disable building any native launchers, you can also pass a `,`-separated list of launcher names e.g. `--force-bash-launchers=lli,graalpython` would disable the `lli` and `graalpython` launchers only.
* `--skip-libraries=true` will disable building any native library, you can also pass a `,`-separated list of library names e.g. `--skip-libraries=polyglot,native-image-agent` would disable `libpolyglot.so` and `libnative-image-agent.so` libraries only.

**Comment by neomatrix369** [comment]
> 8GB is too tight to build non-trivial native images at the moment
> 
> If you don't build a native-image of graalpython, it will have slower start-up.
> 
> * In the `vm` directory, running `mx graalvm-show` should give you an overview of what is being built and in particular, you will see the various native-images (native launchers & libraries).
> * `--force-bash-launchers=true` will disable building any native launchers, you can also pass a `,`-separated list of launcher names e.g. `--force-bash-launchers=lli,graalpython` would disable the `lli` and `graalpython` launchers only.
> * `--skip-libraries=true` will disable building any native library, you can also pass a `,`-separated list of library names e.g. `--skip-libraries=polyglot,native-image-agent` would disable `libpolyglot.so` and `libnative-image-agent.so` libraries only.

Thanks for these combinations, in your view of all the graal plugins (runtimes replacements) which ones are the heavy contenders that should be added to the `--force-bash-launchers`? we have seen graalpython being heavy.

I can always try with all of them disabled and then slowly enabled them.

This is a good option to have! Its closer to what I was thinking in terms of quick and in-depth builds.
