### ISSUE TITLE
Roadmap for development

### ISSUE THREAD

**Issue by nimish** [graalvm/graalpython#97]
Is there a roadmap for where graalpython is and isn't going? Something along the lines of current compatibility and what's missing (and what won't be implemented).

And/or a public issue tracker (some issues appears to have references to an "internal" one)

**Comment by timfel** [comment]
We will have to continue to use the internal issue tracker. However, we will make milestones for upcoming releases with the current planning. This will at least give everyone an idea what's being worked on in the next quarter.

**Comment by erickj** [comment]
Hey there,

It's really exciting to see that this is a VERY active project. Seeing a dozen commits/day from multiple commiters is a reassuring sign that the inject is progressing.

But is this roadmap (or any recent update on graal-python) available anywhere?

Thanks for the good work!
